export enum ActionNoteType {
    ADD_NOTE= 'ADD_NOTE',
    DELETE_ACTIVE_NOTE= 'DELETE_ACTIVE_NOTE',
    CHANGE_ACTIVE_NOTE_INDEX= 'CHANGE_ACTIVE_NOTE_INDEX'
}

export enum ActionGlobalType {
    CHANGE_IS_DARK_MODE = 'CHANGE_IS_DARK_MODE',
    CHANGE_NOTES_OPEN = 'CHANGE_NOTES_OPEN'
}